# Generated by Django 2.2.6 on 2022-03-14 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ingredients', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(default=datetime.date(2022, 3, 14))),
                ('updated', models.DateTimeField(default=datetime.date(2022, 3, 14))),
                ('preparation_time', models.IntegerField(null=True)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
