# Generated by Django 2.2.6 on 2022-03-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_schedule_alter_recipe_created_alter_recipe_updated'),
        ('jedzonko', '0003_auto_20220315_1411'),
        ('jedzonko', '0002_auto_20220315_1259'),
    ]

    operations = [
    ]
