# Generated by Django 2.2.6 on 2022-03-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0005_auto_20220316_1546'),
        ('jedzonko', '0005_recipe_preparation'),
    ]

    operations = [
    ]
