# Generated by Django 2.2.6 on 2022-03-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_merge_20220316_1629')
    ]

    operations = [
    ]
