# Generated by Django 2.2.6 on 2022-03-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0007_merge_20220316_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayname',
            name='name',
            field=models.CharField(choices=[('Mon', 'Poniedziałek'), ('Tue', 'Wtorek'), ('Wed', 'Środa'), ('Thu', 'Czwartek'), ('Fri', 'Piątek'), ('Sat', 'Sobota'), ('Sun', 'Niedziela')], max_length=3),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
