# Generated by Django 2.2.6 on 2022-03-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0008_auto_20220316_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='meal_name',
            field=models.CharField(choices=[(1, 'Śniadanie'), (2, 'Drugie śniadanie'), (3, 'Lunch'), (4, 'Obiad'), (5, 'Podwieczorek'), (6, 'Kolacja'), (7, 'Nocne podjadanie')], max_length=60),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='order',
            field=models.IntegerField(),
        ),
    ]
