# Generated by Django 2.2.6 on 2022-03-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0009_auto_20220316_1836'),
        ('jedzonko', '0006_merge_20220316_1755'),
    ]

    operations = [
    ]
