# Generated by Django 2.2.6 on 2022-03-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0011_auto_20220317_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayname',
            name='name',
            field=models.CharField(choices=[('Mon', 'Poniedziałek'), ('Tue', 'Wtorek'), ('Wed', 'Środa'), ('Thu', 'Czwartek'), ('Fri', 'Piątek'), ('Sat', 'Sobota'), ('Sun', 'Niedziela')], max_length=3),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
