# Generated by Django 4.0.3 on 2022-03-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_merge_20220316_1632'),
        ('jedzonko', '0012_auto_20220317_1344'),
    ]

    operations = [
    ]
