# Generated by Django 2.2.6 on 2022-03-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_merge_20220316_1632'),
        ('jedzonko', '0012_auto_20220317_1344'),
    ]

    operations = [
    ]
