# Generated by Django 2.2.6 on 2022-03-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0013_merge_20220318_1050'),
        ('jedzonko', '0013_merge_20220318_1329'),
    ]

    operations = [
    ]
